### ISSUE TITLE
MN -> PDF: Unable to build PDF for "bs-7273-4-2015-A1-2021"

### ISSUE THREAD

**Issue by manuel489** [metanorma/mn2pdf#103]
*In relation to https://github.com/metanorma/metanorma-bsi/issues/30*

According to my tests, it seems that PDF format is not supporting multi-paragraph content in commentary notes (`[NOTE,type=commentary,...]`)

Part of the error mesasge:
````
        at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:485)
        at org.metanorma.fop.PDFGenerator.runFOP(PDFGenerator.java:423)
        at org.metanorma.fop.PDFGenerator.convertmn2pdf(PDFGenerator.java:309)
        at org.metanorma.fop.PDFGenerator.process(PDFGenerator.java:192)
        at org.metanorma.fop.mn2pdf.main(mn2pdf.java:174)
XSL-FO file for debugging saved into: D:\Trabajo\Metanorma\mn-samples-bsi\sources.mnconvert\bs-codes-of-practice\bs-7273-4-2015-A1-2021\document.pdf.fo.debug.xml
make: *** [Makefile:45: pdf] Error 127

````

**Comment by Intelligent2013** [comment]
I have two issues:
- unable to generate xml:
`C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/relaton-bsi-1.9.0/lib/relaton_bsi/scrapper.rb:124:in fetch_docid': undefined method `[]' for nil:NilClass (NoMethodError)`

After commenting the last item in `99-bibliography.adoc `:
```adoc
* [[[ref_45,BS EN ISO 9001]]], _Quality systems – Requirements_
```
the presentation xml generates ok. Looks like this is relaton issue.

- unable to generate PDF due the error:
`javax.xml.transform.TransformerException: org.apache.fop.fo.ValidationException: null:261:34: A table-cell is spanning more rows than available in its parent element.`

Issue relates to the 'Table 1' adoc generation. Fixed.

**Comment by manuel489** [comment]
Relaton issue is reported in https://github.com/relaton/relaton-bsi/issues/5
