### ISSUE TITLE
(URGENT) Crash when a source code block specifies an unknown language

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn2pdf#115]
When an unknown source code type is used, mn2pdf crashes critically.

This should warn but not fail. (possibly to be warned in Metanorma core as well)

This is a bug in mn2pdf's code syntax highlighting functionality.

```adoc
# This works
[source,html]
----
...
----

# This crashes
[source,express]
----
...
----
```

```sh
Could not find the language 'express', did you forget to load/include a language module?
Could not find the language 'express', did you forget to load/include a language module?
Could not find the language 'express', did you forget to load/include a language module?
Could not find the language 'express', did you forget to load/include a language module?
Could not find the language 'express', did you forget to load/include a language module?
Could not find the language 'express', did you forget to load/include a language module?
Could not find the language 'express', did you forget to load/include a language module?
Exception in thread "main" java.lang.StackOverflowError
	at org.apache.xpath.VariableStack.getLocalVariable(VariableStack.java:375)
	at org.apache.xpath.operations.Variable.execute(Variable.java:216)
	at org.apache.xpath.operations.Variable.execute(Variable.java:188)
	at org.apache.xpath.functions.FuncConcat.execute(FuncConcat.java:50)
	at org.apache.xpath.functions.FuncSubstringBefore.execute(FuncSubstringBefore.java:46)
	at org.apache.xpath.Expression.executeCharsToContentHandler(Expression.java:313)
	at org.apache.xalan.templates.ElemValueOf.execute(ElemValueOf.java:274)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2402)
	at org.apache.xalan.templates.ElemChoose.execute(ElemChoose.java:141)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2402)
	at org.apache.xalan.templates.ElemLiteralResult.execute(ElemLiteralResult.java:1376)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2402)
	at org.apache.xalan.templates.ElemIf.execute(ElemIf.java:162)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2402)
	at org.apache.xalan.templates.ElemTemplate.execute(ElemTemplate.java:394)
	at org.apache.xalan.templates.ElemCallTemplate.execute(ElemCallTemplate.java:248)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2402)
```

_Originally posted by @ronaldtse in https://github.com/metanorma/iso-10303-detached-docs/issues/92#issuecomment-1092399447_

**Comment by Intelligent2013** [comment]
There was stackoverflow issue in recursive template calling in xslt for long sourcecode text (https://github.com/metanorma/iso-10303-detached-docs/issues/92#issuecomment-1092425390).
Fixed in xslt.

**Comment by ronaldtse** [comment]
Confirmed, thanks.
