### ISSUE TITLE
mn2pdf crashes sometimes when 'add_math_as_text' is true

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn2pdf#116]
Document example: NIST.SP.800-90B

```
java.lang.IndexOutOfBoundsException: Index: 4, Size: 4
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at org.apache.fop.render.intermediate.IFStructureTreeBuilder.replayEventsForPageSequence(IFStructureTreeBuilder.java:192)
        at org.apache.fop.render.intermediate.IFSerializer.startPageSequence(IFSerializer.java:278)
        at org.apache.fop.render.intermediate.IFRenderer.startPageSequence(IFRenderer.java:524)
        at org.apache.fop.area.RenderPagesModel.checkPreparedPages(RenderPagesModel.java:172)
        at org.apache.fop.area.RenderPagesModel.endDocument(RenderPagesModel.java:258)
        at org.apache.fop.area.AreaTreeHandler.endDocument(AreaTreeHandler.java:342)
        at org.apache.fop.fo.DelegatingFOEventHandler.endDocument(DelegatingFOEventHandler.java:94)
        at org.apache.fop.accessibility.fo.FO2StructureTreeConverter.endDocument(FO2StructureTreeConverter.java:160)
        at org.apache.fop.fo.FOTreeBuilder.endDocument(FOTreeBuilder.java:170)
        at org.apache.xalan.transformer.TransformerIdentityImpl.endDocument(TransformerIdentityImpl.java:963)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endDocument(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
        at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:485)
        at org.metanorma.fop.PDFGenerator.generateFOPIntermediateFormat(PDFGenerator.java:628)
        at org.metanorma.fop.PDFGenerator.runFOP(PDFGenerator.java:425)
        at org.metanorma.fop.PDFGenerator.convertmn2pdf(PDFGenerator.java:394)
        at org.metanorma.fop.PDFGenerator.process(PDFGenerator.java:272)
        at org.metanorma.fop.mn2pdf.main(mn2pdf.java:334)
```

mn2pdf crashes even when xml doesn't contain mathml.
Error occurs on IF (intermediate format) xml generation.

**Comment by Intelligent2013** [comment]
The error occurs in the concrete xslt (nisp.sp) due the code:
```xml
<fo:marker marker-class-name="annex_number"><xsl:value-of select="substring-after(nist:title/@xref, ' ')"/></fo:marker>
...
<fo:retrieve-marker retrieve-class-name="annex_number"/>
```

**Comment by Intelligent2013** [comment]
Fixed.
