### ISSUE TITLE
mn2pdf doesn't download Noto fonts in some cases

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn2pdf#127]
```
[INFO] XSL-FO file preparation...
processing time: 2а056 milliseconds
Transforming to PDF...
java.io.IOException: Can't read C:\Users\testuser\.metanorma\fonts\NotoSerif-Bold.ttf
        at java.awt.Font.createFont(Unknown Source)
        at org.metanorma.fop.fontConfig.registerFont(fontConfig.java:781)
        at org.metanorma.fop.fontConfig.lambda$updateFontsForGraphicsEnvironment$28(fontConfig.java:76
        at java.util.ArrayList.forEach(Unknown Source)
        at org.metanorma.fop.fontConfig.updateFontsForGraphicsEnvironment(fontConfig.java:768)
        at org.metanorma.fop.fontConfig.updateConfig(fontConfig.java:446)
        at org.metanorma.fop.fontConfig.getConfig(fontConfig.java:737)
        at org.metanorma.fop.PDFGenerator.runFOP(PDFGenerator.java:475)
        at org.metanorma.fop.PDFGenerator.convertmn2pdf(PDFGenerator.java:420)
        at org.metanorma.fop.PDFGenerator.process(PDFGenerator.java:307)
        at org.metanorma.fop.mn2pdf.main(mn2pdf.java:341)
```

**Comment by Intelligent2013** [comment]
Fixed.
