### ISSUE TITLE
Apache FOP 2.8 upgrade

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn2pdf#159]
Apache FOP version 2.8 released 9 Nov 2022.

Updates:
- https://xmlgraphics.apache.org/fop/2.8/releaseNotes_2.8.html
- https://xmlgraphics.apache.org/fop/2.8/changes_2.8.html

To do:
- [x] update FOP sources integrated in mn2pdf
- [x]  investigate how this patches impact on work:
   - [x] [FOP-3078](https://issues.apache.org/jira/browse/FOP-3078): Fix position of macron glyph (also https://issues.apache.org/jira/browse/FOP-3065, https://issues.apache.org/jira/browse/FOP-3063), this patch integrated earlier already
   - [x] [FOP-3085](https://issues.apache.org/jira/browse/FOP-3085): Remove Xalan (no affect)
   - [x] [FOP-3072](https://issues.apache.org/jira/browse/FOP-3072): Empty link url gives NPE (has affect on the issue https://github.com/metanorma/mn2pdf/issues/159#issuecomment-1509895335)
   - [x] [FOP-3091](https://issues.apache.org/jira/browse/FOP-3091): Add transparency color support (ok, no affect on https://github.com/metanorma/metanorma-bipm/issues/188)
- from Apache FOP version 2.6:
   - [ ] ~[FOP-2994](https://issues.apache.org/jira/browse/FOP-2994): Support OTF/TTF SVG fonts~ (the issue relates to the SVG fonts (kind of font), not fonts from SVG)
- [ ] test PDF generation - compare current generated PDF and PDF after update to v2.8

**Comment by Intelligent2013** [comment]
Error occurs:
```
Exception in thread "main" java.lang.NoSuchFieldError: RAW_PDF
        at org.apache.fop.render.afp.AFPImageHandlerRawStream.<clinit>(AFPImageHandlerRawStream.java:43)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at org.apache.xmlgraphics.util.Service.providers(Service.java:85)
        at org.apache.fop.render.ImageHandlerRegistry.discoverHandlers(ImageHandlerRegistry.java:163)
        at org.apache.fop.render.ImageHandlerRegistry.<init>(ImageHandlerRegistry.java:68)
        at org.apache.fop.apps.FopFactory.<init>(FopFactory.java:104)
        at org.apache.fop.apps.FopFactory.newInstance(FopFactory.java:124)
        at org.apache.fop.apps.FopFactoryBuilder.build(FopFactoryBuilder.java:124)
        at org.apache.fop.apps.FopFactory.newInstance(FopFactory.java:137)
        at org.metanorma.fop.PDFGenerator.generateFOPIntermediateFormat(PDFGenerator.java:697)
        at org.metanorma.fop.PDFGenerator.setTablesWidths(PDFGenerator.java:1172)
        at org.metanorma.fop.PDFGenerator.convertmn2pdf(PDFGenerator.java:410)
        at org.metanorma.fop.PDFGenerator.process(PDFGenerator.java:305)
        at org.metanorma.fop.mn2pdf.main(mn2pdf.java:345)
```

**Comment by Intelligent2013** [comment]
> Exception in thread "main" java.lang.NoSuchFieldError: RAW_PDF

Fixed.

**Comment by Intelligent2013** [comment]
ISO 80000 PDF generation error:
```
[ERROR] Error while rendering page 12. Reason: java.lang.NullPointerException
Can't obtain tables widths information: {0}
```

**Comment by Intelligent2013** [comment]
Error occurs due the element `<nav:goto-xy id="t10-2"` in `<page-trailer>`. Left - IF generated by Apache FOP 2.8, right - generated by Apache FOP 2.5 (current):
![image](https://user-images.githubusercontent.com/5559926/232237729-90de0014-6bc4-4cf9-9b9e-cc164da609e8.png)

(IF generated for the tables element only on the 1st step of auto-layout algorithm. Element `<bookmark id="t10-2"/>` is missing in this temporarily XML).
I'll add the exception.

**Comment by Intelligent2013** [comment]
BIPM PDF generation failed:
![image](https://user-images.githubusercontent.com/5559926/232240807-b48246b6-45aa-4626-950e-0f40435282e8.png)

Only Extra-Light font embedded:
![image](https://user-images.githubusercontent.com/5559926/232240916-c3e7ee13-5a53-4b95-8896-26211e89eddb.png)

![image](https://user-images.githubusercontent.com/5559926/232241014-dc687d3e-564b-47e3-a048-8e1c0cc808c2.png)
![image](https://user-images.githubusercontent.com/5559926/232241086-f5a70dae-8f44-4830-bdb6-2afe37db4760.png)

Previous version (Apache FOP 2.5):
![image](https://user-images.githubusercontent.com/5559926/232241402-347a33f3-697d-45d7-8ac9-34851469eca5.png)

I'll investigate what's happened.

**Comment by Intelligent2013** [comment]
Apache FOP 2.5:
```
Page 20: Unresolved ID reference "PV57_5" found.
Page 25: Unresolved ID reference "PV70_2" found.
Page 31: Unresolved ID reference "CR1979-6" found.
Page 31: Unresolved ID reference "PV41_h" found.
Page 33: Unresolved ID reference "CR1979-6" found.
...
```

Apache FOP 2.8 - no warnings.

**Comment by Intelligent2013** [comment]
The messages `Page NN: Unresolved ID reference ...` removed in the update
```
https://gitbox.apache.org/repos/asf?p=xmlgraphics-fop.git;a=commit;h=63c0ce941e58f3673a586527e1669639494ecf6e
```
in the class `RenderPagesModel.java` for fixing issue https://issues.apache.org/jira/projects/FOP/issues/FOP-3048?filter=allissues.
And looks like it has affect on the PDF fonts errors due the changes in `DocumentNavigationHandler.java`.
(https://github.com/apache/xmlgraphics-fop/commit/63c0ce941e58f3673a586527e1669639494ecf6e)
I'll restore the previous version from Apache FOP 2.7.

**Comment by Intelligent2013** [comment]
I've raised a ticket https://issues.apache.org/jira/browse/FOP-3128

**Comment by Intelligent2013** [comment]
Apache FOP 2.8 can't find the external images on the disk:
```
Image not found. URI: file:D:\Work\Metanorma\XML\PAS117_7341\images/coverpage.png. (No context info available)
Image not found. URI: file:D:\Work\Metanorma\XML\PAS117_7341\images/logo_aviva.png. (See position 2:2549)
Image not found. URI: file:D:\Work\Metanorma\XML\PAS117_7341\images/logo_barclays.png. (See position 4:1513)
Image not found. URI: file:D:\Work\Metanorma\XML\PAS117_7341\images/logo_city_of_london.png. (See position 6:1519)
Image not found. URI: file:D:\Work\Metanorma\XML\PAS117_7341\images/logo_hermes.png. (See position 8:1623)
Image not found. URI: file:D:\Work\Metanorma\XML\PAS117_7341\images/logo_hsbc.png. (See position 10:1509)
Image not found. URI: file:D:\Work\Metanorma\XML\PAS117_7341\images/logo_lloyds.png. (See position 12:1511)
Image not found. URI: file:D:\Work\Metanorma\XML\PAS117_7341\images/img_1.png. (See position 71:4251)
Image not found. URI: file:D:\Work\Metanorma\XML\PAS117_7341\images/fig_1.png. (See position 74:224)
Image not found. URI: file:D:\Work\Metanorma\XML\PAS117_7341\images/fig_2.png. (See position 84:224)
Image not found. URI: file:D:\Work\Metanorma\XML\PAS117_7341\images/img_2.png. (See position 192:6253)
Image not found. URI: file:D:\Work\Metanorma\XML\PAS117_7341\images/img_3.png. (See position 244:1485)
Image not found. URI: file:D:\Work\Metanorma\XML\PAS117_7341\images/img_4.png. (See position 361:1431)
Image not found. URI: file:D:\Work\Metanorma\XML\PAS117_7341\images/img_5.png. (See position 463:1378)
Image not found. URI: file:D:\Work\Metanorma\XML\PAS117_7341\images/img_6.png. (See position 557:1341)
```
Will find the issue.

**Comment by Intelligent2013** [comment]
`Image not found` issue fixed, added the prefix `file:///`.

**Comment by Intelligent2013** [comment]
All found issues fixed.
Done in mn2pdf v1.67 (https://github.com/metanorma/mn2pdf/releases/tag/v1.67)
