### ISSUE TITLE
Missing some errors in .err log

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn2pdf#173]
From https://github.com/metanorma/annotated-express/pull/114.

The errors about missing source files for embedding are missing in the .err log, it show only on console:
```
javax.xml.transform.TransformerException: org.xml.sax.SAXException: Error adding embedded file: file:D:\Work\Metanorma\XML\ISO127_AnnotatedExpress\action_schema.exp
org.apache.fop.render.intermediate.IFException: Error adding embedded file: file:D:\Work\Metanorma\XML\ISO127_AnnotatedExpress\action_schema.exp
	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:502)
	at org.metanorma.fop.PDFGenerator.runFOP(PDFGenerator.java:560)
	at org.metanorma.fop.PDFGenerator.convertmn2pdf(PDFGenerator.java:447)
	at org.metanorma.fop.PDFGenerator.process(PDFGenerator.java:310)
	at org.metanorma.fop.mn2pdf.main(mn2pdf.java:345)
Caused by: org.xml.sax.SAXException: Error adding embedded file: file:D:\Work\Metanorma\XML\ISO127_AnnotatedExpress\action_schema.exp
org.apache.fop.render.intermediate.IFException: Error adding embedded file: file:D:\Work\Metanorma\XML\ISO127_AnnotatedExpress\action_schema.exp
	at org.apache.fop.render.intermediate.IFParser$Handler.handleIFException(IFParser.java:386)
	at org.apache.fop.render.intermediate.IFParser$Handler.handleExternallyGeneratedObject(IFParser.java:833)
	at org.apache.fop.render.intermediate.IFParser$Handler.endElement(IFParser.java:403)
	at org.apache.xalan.transformer.TransformerIdentityImpl.endElement(TransformerIdentityImpl.java:1102)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
```

**Comment by Intelligent2013** [comment]
Fixed.
