### ISSUE TITLE
Unhandled exception when cannot connect to X11 window server

### ISSUE THREAD

**Issue by maxirmx** [metanorma/mn2pdf#182]
I see it on WSL (Windows Subsystem for Linux) when metanorma snap is used
IMHO the call
```
GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
```
at ```org.metanorma.fop.fontConfig.updateFontsForGraphicsEnvironment(fontConfig.java:784)```  shall be  protected against exception since Graphics Environment may be "missing"

```
Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using ':0.0' as the value of the DISPLAY variable.
        at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
        at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
        at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
        at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
        at org.metanorma.fop.fontConfig.updateFontsForGraphicsEnvironment(fontConfig.java:784)
        at org.metanorma.fop.fontConfig.updateConfig(fontConfig.java:455)
        at org.metanorma.fop.fontConfig.getConfig(fontConfig.java:763)
        at org.metanorma.fop.PDFGenerator.setTablesWidths(PDFGenerator.java:1146)
        at org.metanorma.fop.PDFGenerator.convertmn2pdf(PDFGenerator.java:390)
        at org.metanorma.fop.PDFGenerator.process(PDFGenerator.java:301)
        at org.metanorma.fop.mn2pdf.main(mn2pdf.java:338)
```

**Comment by maxirmx** [comment]
Ref   https://github.com/metanorma/packed-mn/issues/200

**Comment by Intelligent2013** [comment]
@maxirmx could you give me the short instruction how can I repeat this error? I use Win10. Thanks.

**Comment by maxirmx** [comment]
@Intelligent2013 
It is user environment which I think I have reproduced (https://github.com/metanorma/packed-mn/issues/200).   If you set up WSL (Windows Subsystem for Linux), install Ubuntu, install metanorma using snap and run his task 
```
git clone https://github.com/iho-ohi/S-102-Product-Specification
cd S-102-Product-Specification
git checkout Developing
cd sources/2.2.0 
metanorma -t iho -x pdf document.adoc
```
you will see this exception. As far as I understood it happens because snap wipes out WSL X11 server emulation. If I install some other X11 server like MobaXTerm (https://stackoverflow.com/questions/61110603/how-to-set-up-working-x11-forwarding-on-wsl2) it works.

**Comment by ronaldtse** [comment]
In any case we should not expect any X11 server.

(from: https://github.com/metanorma/packed-mn/issues/200#issuecomment-1457963279)

In the case for the X11 error (well there is no X11 server for most environments we run anyway). Perhaps in this case there is some environment variable (display related?) that causes Java to look for a X11 connection.

Maybe the `DISPLAY` environment variable is present? It is commonly set to `DISPLAY=:0.0`.

**Comment by maxirmx** [comment]
I guess mn2pdf works fine when there is no X11 server.
This one is a complex issue.  WSL creates X11 server instance but snap mangles X11 server configuration.
There are similar issues around (https://github.com/microsoft/WSL/issues/7006 and others), I tried to follow some advices but nothing helped

**Comment by Intelligent2013** [comment]
From https://stackoverflow.com/questions/10165761/java-cant-connect-to-x11-window-server-using-localhost10-0-as-the-value-of-t:
> You need to specify the [-Djava.awt.headless=true](http://www.oracle.com/technetwork/articles/javase/headless-136834.html) parameter at startup time.

In some GH .yml GH we have `JAVA_OPTS: "java.awt.headless=true"` - see https://github.com/search?q=org%3Ametanorma+headless%3Dtrue&type=code

Also: https://stackoverflow.com/questions/41067235/what-is-the-benefit-of-setting-java-awt-headless-true

**Comment by Intelligent2013** [comment]
@maxirmx is there a way to specify `-Djava.awt.headless=true` or set the environment variable `JAVA_OPTS: "java.awt.headless=true"` somewhere?

**Comment by maxirmx** [comment]
I believe it can be added to mn2pdf-ruby
@CAMOBAP, can you help us, please ?

**Comment by ronaldtse** [comment]
@maxirmx I believe @CAMOBAP has fixed this in https://github.com/metanorma/mn2pdf-ruby/pull/35 , can you help verify? Thanks.

**Comment by CAMOBAP** [comment]
@ronaldtse it's not released yet, I propose to review https://github.com/metanorma/mn2pdf-ruby/pull/36 too and I will release them together

**Comment by maxirmx** [comment]
Agree with @CAMOBAP
plus we need to find a solution for https://github.com/metanorma/mn2pdf/issues/183

**Comment by CAMOBAP** [comment]
@maxirmx I'm not sure that I will able to find the solution quickly. And I think it will be on snap level

**Comment by maxirmx** [comment]
> I'm not sure that I will able to find the solution quickly. And I think it will be on snap level
I believe it is the real error that affects the customer.  It does not look like he faces X11 server issues, permissions only.
