### ISSUE TITLE
Exception: java.awt.FontFormatException: bad pfa font

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn2pdf#193]
Source issue: https://github.com/metanorma/metanorma-bipm/issues/283
```
[mn2pdf] [INFO] Generation of Intermediate Format with information about the table's widths ...
[mn2pdf] java.awt.FontFormatException: bad pfa font
[mn2pdf] 	at java.desktop/sun.font.Type1Font.verifyPFA(Type1Font.java:324)
[mn2pdf] 	at java.desktop/sun.font.Type1Font.verify(Type1Font.java:302)
[mn2pdf] 	at java.desktop/sun.font.Type1Font.<init>(Type1Font.java:172)
[mn2pdf] 	at java.desktop/sun.font.SunFontManager.createFont2D(SunFontManager.java:2223)
[mn2pdf] 	at java.desktop/java.awt.Font.<init>(Font.java:644)
[mn2pdf] 	at java.desktop/java.awt.Font.createFont(Font.java:1250)
[mn2pdf] 	at org.metanorma.fop.fontConfig.registerFont(fontConfig.java:837)
[mn2pdf] 	at org.metanorma.fop.fontConfig.lambda$updateFontsForGraphicsEnvironment$33(fontConfig.java:807)
[mn2pdf] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[mn2pdf] 	at org.metanorma.fop.fontConfig.updateFontsForGraphicsEnvironment(fontConfig.java:806)
[mn2pdf] 	at org.metanorma.fop.fontConfig.updateConfig(fontConfig.java:463)
[mn2pdf] 	at org.metanorma.fop.fontConfig.getConfig(fontConfig.java:774)
[mn2pdf] 	at org.metanorma.fop.PDFGenerator.setTablesWidths(PDFGenerator.java:1147)
[mn2pdf] 	at org.metanorma.fop.PDFGenerator.convertmn2pdf(PDFGenerator.java:390)
[mn2pdf] 	at org.metanorma.fop.PDFGenerator.process(PDFGenerator.java:301)
[mn2pdf] 	at org.metanorma.fop.mn2pdf.main(mn2pdf.java:338)
```

This isn't critical error (presumably occurs on MacOS for installed old `fontist` ms fonts)

To do:
- [x] investigate why it happens
- [x] it is possible to remove  this warning or not?

**Comment by Intelligent2013** [comment]
> [ ] investigate why it happens

Each system font should be 'registered' in Java Graphics Environment. The warning occurs when Java tries to register Type1 font, but something wrong in the format. From `https://www.javatips.net/api/ae-awt-master/src/ae/sun/font/Type1Font.java`:
```java
private void verifyPFA(ByteBuffer bb) throws FontFormatException {
        if (bb.getShort() != 0x2521) { // 0x2521 is %!
            throw new FontFormatException("bad pfa font");
        }
```
I can't find which is the font causes this warning (https://github.com/metanorma/mn-native-pdf/pull/557). Looks like, this issue occurs on the particular machine. So, I've added the warning with the problematic font file name.

**Comment by Intelligent2013** [comment]
Done in mn2pdf v1.69.

**Comment by Intelligent2013** [comment]
The error occurs on my machine (WIn10) after the fonts unpacking from [noto-fonts-latn-1.1.zip](https://github.com/fontist/noto-fonts/releases/download/v1.1/noto-fonts-latn-1.1.zip)

```
java.awt.FontFormatException: bad pfa font
	at sun.font.Type1Font.verifyPFA(Type1Font.java:322)
	at sun.font.Type1Font.verify(Type1Font.java:300)
	at sun.font.Type1Font.<init>(Type1Font.java:173)
	at sun.font.SunFontManager.createFont2D(SunFontManager.java:2488)
	at java.awt.Font.<init>(Font.java:615)
	at java.awt.Font.createFont(Font.java:1056)
	at org.metanorma.fop.fontConfig.registerFont(fontConfig.java:982)
	at org.metanorma.fop.fontConfig.lambda$updateFontsForGraphicsEnvironment$33(fontConfig.java:952)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.metanorma.fop.fontConfig.updateFontsForGraphicsEnvironment(fontConfig.java:951)
	at org.metanorma.fop.fontConfig.updateConfig(fontConfig.java:596)
	at org.metanorma.fop.fontConfig.getConfig(fontConfig.java:907)
	at org.metanorma.fop.PDFGenerator.setTablesWidths(PDFGenerator.java:1193)
	at org.metanorma.fop.PDFGenerator.convertmn2pdf(PDFGenerator.java:415)
	at org.metanorma.fop.PDFGenerator.process(PDFGenerator.java:308)
	at org.metanorma.fop.mn2pdf.main(mn2pdf.java:345)
WARNING: error in the font 'C:\Users\TestUser\.fontist\fonts\NotoColorEmoji.ttf' registering.
```

The file `NotoColorEmoji.ttf` is HTML file:
```html

<!DOCTYPE html>
<html lang="en" data-color-mode="auto" data-light-theme="light" data-dark-theme="dark" data-a11y-animated-images="system">
  <head>
    <meta charset="utf-8">
```

**Comment by Intelligent2013** [comment]
No need to more processing here. The warning in the `...pdf.err` is enough:
```
WARNING: error in the font 'C:\Users\TestUser\.fontist\fonts\NotoColorEmoji.ttf' registering.
```
