### ISSUE TITLE
App crashes for ISO 10303-104 PDF generation due StackOverflowError error

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn2pdf#23]
See metanorma/mn-native-pdf#148
```
Exception in thread "main" java.lang.StackOverflowError
	at org.apache.xpath.XPathContext.getCurrentNodeList(XPathContext.java:1018)
	at org.apache.xpath.functions.FuncCurrent.execute(FuncCurrent.java:55)
	at org.apache.xpath.axes.FilterExprIteratorSimple.executeFilterExpr(FilterExprIteratorSimple.java:123)
	at org.apache.xpath.axes.FilterExprWalker.setRoot(FilterExprWalker.java:131)
	at org.apache.xpath.axes.WalkingIterator.setRoot(WalkingIterator.java:157)
	at org.apache.xpath.axes.NodeSequence.setRoot(NodeSequence.java:265)
	at org.apache.xpath.axes.LocPathIterator.asIterator(LocPathIterator.java:269)
```

**Comment by Intelligent2013** [comment]
The solution: add -Xss5m into command line:
`java -Xss5m -jar target/mn2pdf-1.10.jar...`

**Comment by Intelligent2013** [comment]
@ronaldtse Fixed.
