### ISSUE TITLE
Optimization: remove the element `emf` via SAX parser

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn2pdf#230]
As titled.
Sample document: `iso-10303-41`.
```
Java used memory size before: 5416608
Java available memory size before: 1903516000
Preparing...
Input: XML (document.presentation.xml)
Input: XSL (iso.international-standard.xsl)
Output: PDF (.\Result\document.presentation.pdf)

Start SourceXMLDocument
Java used memory size before: 5416608
Java available memory size before: 1903516000
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3332)
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
        at java.lang.StringBuilder.append(StringBuilder.java:142)
```

**Comment by Intelligent2013** [comment]
Done in https://github.com/metanorma/mn2pdf/releases/tag/v1.80.
