### ISSUE TITLE
App crashes for ISO 10303-104 PDF generation due invalid XML character

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn2pdf#24]
See https://github.com/metanorma/mn-native-pdf/issues/148

```
javax.xml.transform.TransformerException: org.xml.sax.SAXParseException; lineNumber: 5470; columnNumber: 19; Character reference "&#55349" is an invalid XML character.
	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:502)
	at com.metanorma.fop.mn2pdf.convertmn2pdf(mn2pdf.java:149)
	at com.metanorma.fop.mn2pdf.main(mn2pdf.java:204)
Caused by: org.xml.sax.SAXParseException; lineNumber: 5470; columnNumber: 19; Character reference "&#55349" is an invalid XML character.
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.scanCharReferenceValue(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:485)
	... 2 more
```

**Comment by Intelligent2013** [comment]
Similar issue discussed here 'Serializing supplementary unicode characters into XML documents with Java': https://stackoverflow.com/questions/11952289/serializing-supplementary-unicode-characters-into-xml-documents-with-java

**Comment by Intelligent2013** [comment]
Issue not resolved yet: https://issues.apache.org/jira/browse/XALANJ-2560

**Comment by Intelligent2013** [comment]
Fixed.
