### ISSUE TITLE
Error Illegal char <"> at index ...

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn2pdf#241]
Source issue: https://github.com/metanorma/metanorma/issues/357

The source presentation XML contains SVG (fragment):
```xml
<span style="background-color: rgb(255 , 255 , 255) ; font-family: &quot;source code pro&quot; , &quot;menlo&quot; , &quot;monaco&quot; , &quot;courier new&quot; , monospace , &quot;menlo&quot; , &quot;monaco&quot; , &quot;courier new&quot; , monospace">
                                   text
                                </span>
```

The error occurs on Win10:
```xml
Illegal char <"> at index 46: C:\Users\TestUser/.fontist/fonts\filenotfound_"source code pro".ttf
java.nio.file.InvalidPathException: Illegal char <"> at index 46: C:\Users\TestUser/.fontist/fonts\filenotfound_"source code pro".ttf
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
```

**Comment by ronaldtse** [comment]
So the problem is our engine is assuming the file name contains double quotes.
