### ISSUE TITLE
"fo:block" is not a valid child of "fo:table-body"! (See position 1032:400)

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/mn2pdf#253]
Failure happens for NIST flavor

```
org.apache.fop.fo.ValidationException: "fo:block" is not a valid child of "fo:table-body"! (See position 1032:400)
	at org.apache.fop.events.ValidationExceptionFactory.createException(ValidationExceptionFactory.java:38)
	at org.apache.fop.events.EventExceptionManager.throwException(EventExceptionManager.java:58)
	at org.apache.fop.events.DefaultEventBroadcaster$1.invoke(DefaultEventBroadcaster.java:173)
	at jdk.proxy2/jdk.proxy2.$Proxy10.invalidChild(Unknown Source)
	at org.apache.fop.fo.FONode.invalidChildError(FONode.java:581)
	at org.apache.fop.fo.FONode.invalidChildError(FONode.java:557)
	at org.apache.fop.fo.flow.table.TablePart.validateChildNode(TablePart.java:175)
	at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.startElement(FOTreeBuilder.java:305)
	at org.apache.fop.fo.FOTreeBuilder$2.run(FOTreeBuilder.java:185)
	at org.apache.fop.fo.FOTreeBuilder$2.run(FOTreeBuilder.java:182)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
	at org.apache.fop.fo.FOTreeBuilder.startElement(FOTreeBuilder.java:181)
	at org.apache.xalan.transformer.TransformerIdentityImpl.startElement(TransformerIdentityImpl.java:1073)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:518)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:376)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2726)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:114)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:542)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:889)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:825)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:485)
	at org.metanorma.fop.PDFGenerator.generateFOPIntermediateFormat(PDFGenerator.java:775)
	at org.metanorma.fop.PDFGenerator.runFOP(PDFGenerator.java:509)
	at org.metanorma.fop.PDFGenerator.convertmn2pdf(PDFGenerator.java:466)
	at org.metanorma.fop.PDFGenerator.process(PDFGenerator.java:301)
	at org.metanorma.fop.mn2pdf.main(mn2pdf.java:338)
```

Full log https://github.com/metanorma/metanorma-cli/actions/runs/9552082732/job/26359330535#step:10:4019

**Comment by Intelligent2013** [comment]
Issue fixed. NIST XSLT updated in https://github.com/metanorma/metanorma-nist.
