### ISSUE TITLE
java.lang.NullPointerException: Parameter msg must not be empty

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/mn2pdf#46]
<details><summary>Full stacktrace</summary>
<p>

```
java.lang.NullPointerException: Parameter msg must not be empty
	at org.krysalis.barcode4j.impl.code39.Code39Bean.generateBarcode(Code39Bean.java:184)
	at org.krysalis.barcode4j.impl.ConfigurableBarcodeGenerator.generateBarcode(ConfigurableBarcodeGenerator.java:174)
	at org.krysalis.barcode4j.image.loader.ImageConverterBarcode2G2D$Graphics2DImagePainterBarcode.paint(ImageConverterBarcode2G2D.java:122)
	at org.apache.fop.render.pdf.PDFImageHandlerGraphics2D.handleImage(PDFImageHandlerGraphics2D.java:99)
	at org.apache.fop.render.intermediate.AbstractIFPainter.drawImage(AbstractIFPainter.java:249)
	at org.apache.fop.render.intermediate.AbstractIFPainter.drawImage(AbstractIFPainter.java:205)
	at org.apache.fop.render.intermediate.AbstractIFPainter.drawImageUsingImageHandler(AbstractIFPainter.java:170)
	at org.apache.fop.render.intermediate.AbstractIFPainter.drawImageUsingDocument(AbstractIFPainter.java:319)
	at org.apache.fop.render.pdf.PDFPainter.drawImage(PDFPainter.java:289)
	at org.apache.fop.render.intermediate.IFRenderer.renderForeignObject(IFRenderer.java:1319)
	at org.apache.fop.render.AbstractRenderer.renderInlineViewport(AbstractRenderer.java:1034)
	at org.apache.fop.render.AbstractPathOrientedRenderer.renderInlineViewport(AbstractPathOrientedRenderer.java:836)
	at org.apache.fop.render.intermediate.IFRenderer.renderInlineViewport(IFRenderer.java:863)
	at org.apache.fop.render.AbstractRenderer.renderInlineArea(AbstractRenderer.java:877)
	at org.apache.fop.render.intermediate.IFRenderer.renderInlineArea(IFRenderer.java:927)
	at org.apache.fop.render.AbstractRenderer.renderLineArea(AbstractRenderer.java:845)
	at org.apache.fop.render.AbstractRenderer.renderBlocks(AbstractRenderer.java:704)
	at org.apache.fop.render.AbstractRenderer.renderBlock(AbstractRenderer.java:758)
	at org.apache.fop.render.intermediate.IFRenderer.renderBlock(IFRenderer.java:999)
	at org.apache.fop.render.AbstractRenderer.renderBlocks(AbstractRenderer.java:689)
	at org.apache.fop.render.AbstractPathOrientedRenderer.renderReferenceArea(AbstractPathOrientedRenderer.java:759)
	at org.apache.fop.render.AbstractRenderer.renderBlock(AbstractRenderer.java:744)
	at org.apache.fop.render.intermediate.IFRenderer.renderBlock(IFRenderer.java:999)
        at org.apache.fop.render.AbstractRenderer.renderBlocks(AbstractRenderer.java:689)
	at org.apache.fop.render.intermediate.IFRenderer.renderBlockViewport(IFRenderer.java:812)
	at org.apache.fop.render.AbstractRenderer.renderBlock(AbstractRenderer.java:737)
	at org.apache.fop.render.intermediate.IFRenderer.renderBlock(IFRenderer.java:999)
	at org.apache.fop.render.AbstractRenderer.renderBlocks(AbstractRenderer.java:689)
	at org.apache.fop.render.AbstractRenderer.renderFlow(AbstractRenderer.java:591)
	at org.apache.fop.render.AbstractPathOrientedRenderer.renderFlow(AbstractPathOrientedRenderer.java:789)
	at org.apache.fop.render.AbstractRenderer.renderMainReference(AbstractRenderer.java:568)
	at org.apache.fop.render.AbstractRenderer.renderBodyRegion(AbstractRenderer.java:433)
	at org.apache.fop.render.AbstractRenderer.renderRegionViewport(AbstractRenderer.java:380)
	at org.apache.fop.render.intermediate.IFRenderer.renderRegionViewport(IFRenderer.java:738)
	at org.apache.fop.render.AbstractRenderer.renderPageAreas(AbstractRenderer.java:345)
	at org.apache.fop.render.AbstractRenderer.renderPage(AbstractRenderer.java:318)
	at org.apache.fop.render.intermediate.IFRenderer.renderPage(IFRenderer.java:587)
	at org.apache.fop.area.RenderPagesModel.renderPage(RenderPagesModel.java:193)
	at org.apache.fop.area.RenderPagesModel.checkPreparedPages(RenderPagesModel.java:174)
	at org.apache.fop.area.RenderPagesModel.addPage(RenderPagesModel.java:146)
	at org.apache.fop.layoutmgr.AbstractPageSequenceLayoutManager.finishPage(AbstractPageSequenceLayoutManager.java:316)
	at org.apache.fop.layoutmgr.PageSequenceLayoutManager.finishPage(PageSequenceLayoutManager.java:243)
	at org.apache.fop.layoutmgr.PageSequenceLayoutManager.activateLayout(PageSequenceLayoutManager.java:147)
	at org.apache.fop.area.AreaTreeHandler.endPageSequence(AreaTreeHandler.java:267)
	at org.apache.fop.fo.DelegatingFOEventHandler.endPageSequence(DelegatingFOEventHandler.java:114)
	at org.apache.fop.accessibility.fo.FO2StructureTreeConverter.endPageSequence(FO2StructureTreeConverter.java:184)
	at org.apache.fop.fo.pagination.PageSequence.endOfNode(PageSequence.java:139)
	at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.endElement(FOTreeBuilder.java:362)
	at org.apache.fop.fo.FOTreeBuilder.endElement(FOTreeBuilder.java:190)
	at org.apache.xalan.transformer.TransformerIdentityImpl.endElement(TransformerIdentityImpl.java:1102)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:485)
	at com.metanorma.fop.mn2pdf.runFOP(mn2pdf.java:292)
	at com.metanorma.fop.mn2pdf.convertmn2pdf(mn2pdf.java:225)
	at com.metanorma.fop.mn2pdf.main(mn2pdf.java:470)
```

</p>
</details>

This happens on Windows only

Full log https://github.com/metanorma/mn-samples-un/runs/1056723747?check_suite_focus=true

I'm not 100% sure that there is a problem with this repo maybe it's related to https://github.com/metanorma/mn2pdf-ruby or other gem, we just need investigate it at start

**Comment by Intelligent2013** [comment]
@CAMOBAP

Error
```
java.lang.NullPointerException: Parameter msg must not be empty
	at org.krysalis.barcode4j.impl.code39.Code39Bean.generateBarcode(Code39Bean.java:184)
```
relates to `barcode` api.  Barcode utilizes value from `/un-standard/bibdata/docidentifier`. If value can't be found, then this exception is raising. I've modelled this situation (by removing docidentifier in my local xml instance) and added a value checking before barcode api calling.

**BUT** you've wrote that
> This happens on Windows only

Looks like it means that source XML file on Windows platform doesn't correct/full or something different than for other platform.

**Comment by CAMOBAP** [comment]
@Intelligent2013 thanks for the investigation, can it be the case if FileNotFound because of the wrong path?

**Comment by Intelligent2013** [comment]
> 
> 
> @Intelligent2013 thanks for the investigation, can it be the case if FileNotFound because of the wrong path?

no, this error occurs when mn2pdf processing xsl-fo xml file yet (after source_xml+xsl processing).

**Comment by CAMOBAP** [comment]
ok, one last question before closing, how `/un-standard/bibdata/docidentifier` this file passed to `mn2pdf.jar`?

**Comment by Intelligent2013** [comment]
This is not a file, it's a XPATH from source XML:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<un-standard xmlns="https://www.metanorma.org/ns/un">
  <bibdata type="standard">
    <title type="main" language="en" format="text/plain">Briefing note on sustainable textile value chains in the garment and footwear domain for SDG12</title>
    <docidentifier>GE.19-04574(E)</docidentifier>
...
```

File passes via `--xml-file` param like this:
```
java -Xss5m -Xmx1024m -jar mn2pdf.jar --xml-file <xmlfile> ....
```

Maybe on Win-platform this XML field docidentifier  is absent. OR namespace in xml is incorrent, it should be `<un-standard xmlns="https://www.metanorma.org/ns/un">`

**Comment by CAMOBAP** [comment]
https://github.com/metanorma/metanorma-un/issues/74 - created for future investigation
