### ISSUE TITLE
Add two-pass feature to produce Indexes without page repeating

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn2pdf#47]
For BIPM PDF.

Preliminary solution:
To prevent on repeating page-numbers for the same term in Index page, need to add two-pass feature into mn2pdf:
- 1st - generate .fo xml 
- 2nd pass - generate FOP intermediate format (https://xmlgraphics.apache.org/fop/2.5/intermediate.html), check that terms on the same page and remove it from .fo file generated on 1st stage.

**Comment by Intelligent2013** [comment]
Index in presentation xml: https://github.com/metanorma/metanorma-bipm/issues/67

**Comment by Intelligent2013** [comment]
Trying to generate an intermediate format (area tree, `at` format):
```
C:\fop-2.5\fop\fop.bat -xml si-brochure-en.presentation.xml -xsl bipm.brochure.presentation.xsl -c metanorma\fonts\pdf_fonts_config.xml.out -at application/pdf at.xml
```
error occurs:
```
SEVERE: org.xml.sax.SAXParseException; systemId: file:/C:/Metanorma/bipm.brochure.presentation.xsl; line
mber: 1192; columnNumber: 41; java.lang.NullPointerException
дек. 21, 2020 10:28:13 PM org.apache.fop.cli.Main startFOP
SEVERE: Exception
org.apache.fop.apps.FOPException: javax.xml.transform.TransformerException: java.lang.NullPointerException
javax.xml.transform.TransformerException: java.lang.NullPointerException
        at org.apache.fop.cli.InputHandler.transformTo(InputHandler.java:296)
        at org.apache.fop.cli.InputHandler.renderTo(InputHandler.java:116)
        at org.apache.fop.cli.Main.startFOP(Main.java:183)
        at org.apache.fop.cli.Main.main(Main.java:214)
Caused by: javax.xml.transform.TransformerException: java.lang.NullPointerException
        at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2407)
        at org.apache.xalan.templates.ElemLiteralResult.execute(ElemLiteralResult.java:1376)
        at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2402)
        at org.apache.xalan.templates.ElemTemplate.execute(ElemTemplate.java:394)
        at org.apache.xalan.templates.ElemCallTemplate.execute(ElemCallTemplate.java:248)
        at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2402)
        at org.apache.xalan.templates.ElemChoose.execute(ElemChoose.java:128)
        at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2402)
        at org.apache.xalan.templates.ElemLiteralResult.execute(ElemLiteralResult.java:1376)
        at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2402)
        at org.apache.xalan.transformer.TransformerImpl.applyTemplateToNode(TransformerImpl.java:2272)
        at org.apache.xalan.transformer.TransformerImpl.transformNode(TransformerImpl.java:1358)
        at org.apache.xalan.transformer.TransformerImpl.transform(TransformerImpl.java:711)
        at org.apache.xalan.transformer.TransformerImpl.transform(TransformerImpl.java:1275)
        at org.apache.xalan.transformer.TransformerImpl.transform(TransformerImpl.java:1253)
        at org.apache.fop.cli.InputHandler.transformTo(InputHandler.java:293)
```
Line #1192:
```xml
<fo:flow flow-name="xsl-region-body">
```

In new intermediate format (`if` format):
```
C:\fop-2.5\fop\fop.bat -xml si-brochure-en.presentation.xml -xsl bipm.brochure.presentation.xsl -c metanorma\fonts\pdf_fonts_config.xml.out -if application/pdf if.xml
```
resulted xml is ok:
```xml
<id name="_1"/>
<text x="-51023" y="13296" foi:struct-ref="4a0">Index</text>
<font size="10000"/>
<text x="0" y="111510" foi:struct-ref="4a2">D</text>
<font style="italic" weight="400" size="10500"/>
<text x="0" y="127020" foi:struct-ref="4a5">Dasein</text>
<font style="normal"/>
<text x="29724" y="127020" foi:struct-ref="4a6">, </text>
<font style="italic"/>
<text x="34974" y="127020" foi:struct-ref="4a7">voir</text>
<font style="normal"/>
<text x="51867" y="127020" foi:struct-ref="4a8"> Emancipation, être</text>
<text x="0" y="139620" foi:struct-ref="4aa"> </text>
<font weight="700" size="10000"/>
<text x="0" y="151721" foi:struct-ref="4ac">E</text>
<font weight="400" size="10500"/>
<text x="0" y="167220" foi:struct-ref="4ae">élongé, </text>
<text x="33210" y="167220" foi:struct-ref="4b0">12</text>
<text x="43710" y="167220" foi:struct-ref="4b1">, </text>
<text x="48960" y="167220" foi:struct-ref="4b3">12</text>
<text x="59460" y="167220" foi:struct-ref="4b4">–</text>
<text x="64710" y="167220" foi:struct-ref="4b5">14</text>
<text x="0" y="179820" foi:struct-ref="4b8">Emancipation, </text>
<text x="63490" y="179820" foi:struct-ref="4ba">12</text>
<text x="73990" y="179820" foi:struct-ref="4bb">, </text>
<text x="79240" y="179820" foi:struct-ref="4bd">12</text>
<text x="14173" y="192420" foi:struct-ref="4bf">dans la France, </text>
<text x="80004" y="192420" foi:struct-ref="4c1">12</text>
<text x="90504" y="192420" foi:struct-ref="4c2">, </text>
<text x="95754" y="192420" foi:struct-ref="4c4">12</text>
<text x="106254" y="192420" foi:struct-ref="4c5">, </text>
<text x="111504" y="192420" foi:struct-ref="4c7">12</text>
<text x="28346" y="205020" foi:struct-ref="4c9">à Paris, </text>
<text x="61849" y="205020" foi:struct-ref="4cb">12</text>
<text x="28346" y="217620" foi:struct-ref="4ce">en Bretagne, </text>
<text x="83972" y="217620" foi:struct-ref="4d0">12</text>
<text x="14173" y="230220" foi:struct-ref="4d4">dans les États-Unis, </text>
<text x="99826" y="230220" foi:struct-ref="4d6">12</text>
<text x="0" y="242820" foi:struct-ref="4da">être</text>
<text x="14173" y="255431" foi:struct-ref="4db">Husserl, </text>
<font style="italic"/>
<text x="51477" y="255431" foi:struct-ref="4dc">voir</text>
<font style="normal"/>
<text x="68370" y="255431" foi:struct-ref="4dd"> zebra, </text>
<font style="italic"/>
<text x="98944" y="255431" foi:struct-ref="4de">voir aussi</text>
<font style="normal"/>
<text x="28346" y="268031" foi:struct-ref="4df">Emancipation, zebra</text>
<text x="28346" y="280631" foi:struct-ref="4e0">en allemand, </text>
<text x="84549" y="280631" foi:struct-ref="4e2">12</text>
<text x="0" y="293231" foi:struct-ref="4e7"> </text>
<font weight="700" size="10000"/>
<text x="0" y="305332" foi:struct-ref="4e9">Z</text>
<font weight="400" size="10500"/>
<text x="0" y="320831" foi:struct-ref="4eb">zebra, </text>
<text x="27949" y="320831" foi:struct-ref="4ed">12</text>
```

Page number (12 in example) in element `text` has reference ` foi:struct-ref="4c1"` to element:
```xml
<fo:page-number-citation foi:struct-id="4c1"/>
```

in the block:
```xml
<fo:block>
	<marked-content foi:struct-id="4bf"/>
	<fo:basic-link fox:alt-text="bm1" foi:struct-id="4c0">
		<fo:inline foi:struct-ref="4c0">
			<fo:page-number-citation foi:struct-id="4c1"/>
		</fo:inline>
	</fo:basic-link>
	<marked-content foi:struct-id="4c2"/>
	<fo:basic-link fox:alt-text="bm1" foi:struct-id="4c3">
		<fo:inline foi:struct-ref="4c3">
			<fo:page-number-citation foi:struct-id="4c4"/>
		</fo:inline>
	</fo:basic-link>
	<marked-content foi:struct-id="4c5"/>
	<fo:basic-link fox:alt-text="bm1" foi:struct-id="4c6">
		<fo:inline foi:struct-ref="4c6">
			<fo:page-number-citation foi:struct-id="4c7"/>
		</fo:inline>
	</fo:basic-link>
	<marked-content foi:struct-id="4c8"/>
	<fo:block>
		<marked-content foi:struct-id="4c9"/>
		<fo:basic-link fox:alt-text="bm1" foi:struct-id="4ca">
			<fo:inline foi:struct-ref="4ca">
				<fo:page-number-citation foi:struct-id="4cb"/>
			</fo:inline>
		</fo:basic-link>
		<marked-content foi:struct-id="4cc"/>
	</fo:block>
	<marked-content foi:struct-id="4cd"/>
	<fo:block>
		<marked-content foi:struct-id="4ce"/>
		<fo:basic-link fox:alt-text="bm1" foi:struct-id="4cf">
			<fo:inline foi:struct-ref="4cf">
				<fo:page-number-citation foi:struct-id="4d0"/>
			</fo:inline>
		</fo:basic-link>
		<marked-content foi:struct-id="4d1"/>
	</fo:block>
	<marked-content foi:struct-id="4d2"/>
</fo:block>
```

Example resulted PDF:
![изображение](https://user-images.githubusercontent.com/5559926/102815757-ee503780-43dd-11eb-9860-a7c228d58886.png)

**Comment by Intelligent2013** [comment]
Main idea.
**1st pass**:
1. on-fly (in xslt) add unique id for each xref in clause[@type = 'index']
2. Generate (in mn2pdf) an intermediate format FOP xml file (IF file).
3. In IF file iterate each element `fo:page-number-citation`:
```xml
<fo:page-number-citation foi:struct-id="4b0"/>
```
and find referenced element `text` with `@foi:struct-ref=@foi:struct-id`:
```xml
<text x="33210" y="167220" foi:struct-ref="4b0">12</text>
```
then get then preceding element `id`/@name:
```xml
<id name="2_1"/>
<text x="33210" y="167220" foi:struct-ref="4b0">12</text>
```

and store each pair in xml on disk (index.xml):
```xml
<index>
<item id="{id/@name}">text/text()</item>
</index>
```

```xml
<index>
<item id="2_1">12</item>
</index>
```

**2nd pass**:
1. pass index.xml from 1st pass to xslt as external parameter `external_index`.
2. remove `xref` element (and following `,`, or preceding `,` if current xref contains range) when next page number is equal to current page number (get page number from external_index)
3. start and end of range should be processed also.
4. try to use recursion processing of elements in `li`, instead of `apply-templates`.

**Comment by Intelligent2013** [comment]
Done in https://github.com/metanorma/mn2pdf/releases/tag/v1.26.
